# Generated by Django 5.0.7 on 2024-07-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_list',
            fields=[
                ('compID', models.AutoField(primary_key=True, serialize=False)),
                ('compName', models.CharField(max_length=255)),
                ('compAddress', models.CharField(max_length=255)),
                ('compCity', models.CharField(max_length=255)),
                ('compState', models.CharField(max_length=255)),
                ('compURL', models.URLField(max_length=255)),
                ('compEstd', models.DateField()),
                ('compType', models.CharField(max_length=255)),
                ('compSize', models.CharField(max_length=255)),
                ('compISIN', models.CharField(max_length=255)),
            ],
        ),
    ]
